Controllers films users
SergeyAseev/java-filmorate pull request #2
Opened 2022-06-30 14:53 UTC by SergeyAseev

Проект готов к проверке

2022-07-01 12:24 UTC, alexache requested changes

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Iterable<Film> findAll() {
(можно лучше) Iterable наверное даже слишком консервативно, List как-то больше подойдет

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
По ТЗ нужно логгировать все операции создания/обновления

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void validate(Film film) {
Не помешает модификатор доступа

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
По ТЗ нужно логгировать все операции создания/обновления

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    Integer id;
Модификаторы доступа не помешают

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Integer id;
Модификатора доступа все равно не помешают здесь

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        validate(user);
По ТЗ нужно логгировать все операции создания/обновления

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        validate(user);
По ТЗ нужно логгировать все операции создания/обновления

2022-07-01 12:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void validate(Film film) {
Не помешает модификатор доступа

2022-07-01 16:58 UTC, SergeyAseev commented
Александр, добавил забытые (в очередной раз) модификаторы доступа и логирование при создании/обновлении фильмов и пользователей.

2022-07-01 16:59 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        validate(user);
done

2022-07-01 16:59 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        validate(user);
done

2022-07-01 16:59 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    Integer id;
done

2022-07-01 17:00 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    void validate(Film film) {
done

2022-07-01 17:00 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        validate(film);
done

2022-07-01 17:00 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Iterable<Film> findAll() {
done

2022-07-02 18:56 UTC, alexache approved these changes
Все ок

2022-07-04 05:52 UTC, merged