Develop
SergeyAseev/java-filmorate pull request #24
Opened 2022-09-02 06:29 UTC by SergeyAseev

Проект готов к проверке

2022-09-03 08:24 UTC, alexache requested changes
Очень объемная и качественная работа!

2022-09-03 08:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        if (findIdDirector(directorId) == null || findIdDirector(directorId).isEmpty()) {
Почему 2 раза делается find? Лучше бы использовать переменные

2022-09-03 08:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                List<Film> films = jdbcTemplate.query(sqlQuery, this::makeFilm, directorId);
Это общая часть, ее можно было бы вынести от этих 2 ветвлений, чтобы не было дублирования

2022-09-03 08:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                film.setMpa(mpaRatingDao.getFilmMpa(film.getId()));
Эти операции довольно странные, почему эти данные не наполняются через join запросы?
Это очень много лишних накладных запросов

2022-09-03 08:24 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserDbService.java
> +        List<User> allUsers = retrieveAllUsers();
Лучше бы часть этой логики перенести на SQL запросы - сразу получить список юзеров со схожими лайками, без прохода в цикле всех юзеров, а уже вторым шагом получать рекоммендации от этих пользователей второым SQL запросом

2022-09-03 12:20 UTC, anatolykalugin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> searchFilmsByDirectorOrName(@RequestParam String query,
Сделано

2022-09-03 12:20 UTC, anatolykalugin commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmDbService.java
> +        } catch (EmptyResultDataAccessException e) {
Сделано

2022-09-03 12:20 UTC, anatolykalugin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +            sql += "WHERE UPPER(f.NAME) REGEXP ? OR UPPER(d.DIRECTOR_NAME) REGEXP ? ORDER BY f.id DESC";
Сделано

2022-09-03 12:20 UTC, anatolykalugin commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        if (option.contains("director") && option.contains("title") && (option.size() == 2)) {
Сделано

2022-09-03 12:27 UTC, anatolykalugin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +
Метод на 52-й строке

2022-09-03 12:27 UTC, anatolykalugin commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
Метод на 51-й строке

2022-09-03 16:15 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FeedDbStorage.java
> +public class FeedDbStorage  implements FeedDao{
Сделал так, чтобы сохранить единообразие в проекте. Данный метод переименован.

2022-09-03 16:16 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FeedDbStorage.java
> +        String sql = "SELECT * FROM FEED where user_id = ? ;";
Готово

2022-09-03 16:38 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                film.setMpa(mpaRatingDao.getFilmMpa(film.getId()));
Данный код сохранился со сдачи ТЗ11. Все говорили, что надо вносить минимальные правки в старый код. Поэтому мы только добавили одну строчку `film.setDirectors(directorDao.getFilmDirectors(film.getId()));` Если можно, то хотелось бы оставить данный код без изменений. По тестам бывают фильмы без рейтинга/жанра. Также наставник советовал выносить все метода работы с другими сущностями в свои классы, что и было сделано.

2022-09-03 19:04 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private List<Director> directors;
Исправил

2022-09-03 19:04 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDao.java
> +    List<Director> getFilmDirectors(Long id);
Исправил

2022-09-03 19:05 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +        if (director.getId() == directorId.getId()) {
Сделал просто проверку на null

2022-09-03 19:05 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +        List<Integer> integers = jdbcTemplate.queryForList(sqlQuery,Integer.class,id);
Изменил

2022-09-03 19:05 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +        final String sqlQuery = "select DIRECTOR_ID from FILMS_DIRECTORS where FILM_ID = ?";
Сделано

2022-09-03 19:06 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        if (findIdDirector(directorId) == null || findIdDirector(directorId).isEmpty()) {
Сделал через переменную

2022-09-03 19:10 UTC, ArtemMironiuk commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                List<Film> films = jdbcTemplate.query(sqlQuery, this::makeFilm, directorId);
не понимаю как это можно вынести? это же два разных запроса

2022-09-04 05:27 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +        log.info("Send post request /reviews {}", review);
готово

2022-09-04 05:29 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select f.* from films f where f.id = " +
готово

2022-09-04 05:49 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format("Отзыв по id=%s не найден!", id), e);
Тогда получается, что проект теряет единый стиль. Если посмотреть на другие классы в папке service, то там везде кидаются аналогичные исключения. Да и сервис ничего и не знает о способе хранения данных. Он в данном случае просто говорит, что данных нет.

2022-09-04 06:53 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    List <Optional<Film>> getRecommendations(long id);
Готово

2022-09-04 07:03 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserDbService.java
> +        List<User> allUsers = retrieveAllUsers();
Команда не придумала адекватного метода через запросы пока что. Ест идея использовать несколько Map<>... - в первую карту записывать всех пользователей и их фильмы, которым они поставили лайка. Потом вторым проходом передавать ID пользователя, который пришел в запросе и для каждого случая считать кол-во пересечений. Т.е. тем самым у нас не будет прохода по пользователям, которые НЕ ставили лайки вообще. Для данной реализации потребуется ввести handler, который будет отвечать только за эти методы.

2022-09-04 08:06 UTC, IvanKondrashkov commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format("Отзыв по id=%s не найден!", id), e);
Добрый день, мне кажется что обрабатывать исключения в одном слое, в данном случае сервисном, это как раз плюс, а не минус.

2022-09-05 10:08 UTC, anatolykalugin commented
В результате работы над групповым проектом были добавлены такой функционал, как поиск фильма по названию или режиссеру, общие фильмы, рекомендации, лента событий, режиссеры, отзывы, удаление пользователей и фильмов, а также вывод самых популярных фильмов по жанрам и годам.

2022-09-05 14:22 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/UserDbService.java
> +        List<User> allUsers = retrieveAllUsers();
`select f.USER_ID, count(f.FILM_ID) rate from LIKES l
	join LIKES f on (l.FILM_ID = f.FILM_ID and l.USER_ID != f.USER_ID)
	join USERS u on l.USER_ID != u.USER_ID
	where l.USER_ID = ? 
	group by f.USER_ID 
	having rate > 1
	order by rate desc
	limit 20`
Вот пример одного запроса, чтобы получить всех юзеров с похожими предпочтениями.
Остается второй запрос получить рекомендации от таких юзеров, такой запрос уже намного легче

2022-09-05 14:23 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format("Отзыв по id=%s не найден!", id), e);
EmptyResultDataAccessException - это ошибка из Spring DAO, то есть очень конкретный способ хранения

2022-09-05 14:46 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select f.* from films f " +
Это все равно запрос со вложенными запросами, хоть и обернутый в джоины. Вложенные запросы тут не нужны
`select * from films f 
   left join MPA m on (f.MPA_ID = m.MPA_ID
   left join DIRECTORS d on (f.DIRECTOR_ID = d.DIRECTOR_ID
   join LIKES lu on (lu.FILM_ID = f.FILM_ID)
   join LIKES lf on (lf.FILM_ID = f.FILM_ID)
   where  lu.USER_ID = ? AND  lf.USER_ID = ?'

2022-09-05 14:46 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                film.setMpa(mpaRatingDao.getFilmMpa(film.getId()));
Методы работы с другими сущностями - это ок, но касается CRUD операций, а не наполнения данными запросов фильмов. то есть сейчас часть запросов делают джоины, а часть нет, и получаются пересечения. Если не хочется слишком менять, то хотя бы проверять, что уже есть данные, и делать запрос к другим дао, только если данных не хватает

2022-09-05 14:48 UTC, alexache requested changes
Осталось всего немного комментариев - отеетом на ваши комментарии, в основном про SQL запросы и Spring DAO exception обработки на уровне сервиса

2022-09-05 20:33 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserDbService.java
> +        List<User> allUsers = retrieveAllUsers();
Спасибо за подсказку. Один член комманды предложил свой вариант.

2022-09-05 20:36 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                List<Film> films = jdbcTemplate.query(sqlQuery, this::makeFilm, directorId);
Спасибо за комментарий! Да, я понял, что можно вынести в константу, добавив ей модификатор доступа. Однако считаю, что это немного затрудняет чтение кода, так как надо смотреть sql-запрос по отдельным частям (ярко осознал, когда понял, что можно сделать еще несколько таких констант в этом же классе).

2022-09-05 20:39 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "select f.* from films f " +
Спасибо за подсказку! Обязательно поделюсь данным запросом с командой!

2022-09-05 20:40 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +            throw new NotFoundException(String.format("Отзыв по id=%s не найден!", id), e);
Готово

2022-09-05 21:02 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +                film.setMpa(mpaRatingDao.getFilmMpa(film.getId()));
Готово. Добавили проверку на null

2022-09-06 08:32 UTC, alexache approved these changes
Мне кажется с рекоммендациями еще есть проблемы, но по сумме сторипоинтов можно сказать, что вы сделали достаточно

2022-09-06 08:32 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/UserDbStorage.java
> +        final String sqlQuery = "SELECT L.FILM_ID FROM LIKES L JOIN LIKES L2 ON L.USER_ID = L2.USER_ID AND L2.USER_ID = L.USER_ID";
L.USER_ID = L2.USER_ID AND L2.USER_ID = L.USER_ID - какой-то самодублирующееся условие, еще хорошо бы проверять. что здесь нет фильмов, которые первоначальный юзер уже оценивал

2023-01-26 20:01 UTC, merged