Add database
SergeyAseev/java-filmorate pull request #5
Opened 2022-07-31 21:46 UTC by SergeyAseev

2022-08-01 19:07 UTC, SergeyAseev commented
ТЗ11 готово к проверке

2022-08-02 14:49 UTC, alexache requested changes
Все очень хорошо, но осталось пару нюансов, которые можно улучшить

2022-08-02 14:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    List<Mpa> retrieveAllMpaRatings();
Мне кажется, что MPA и жанры можно было бы расположить в своих отдельных сервисах

2022-08-02 14:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmDbService.java
> +        return filmStorage.retrieveAllFilms().stream()
Такую сортировку с ограничение по количеству записей лучше бы сделать сразу в SQL запросе

2022-08-02 14:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "SELECT * FROM films WHERE id = ?";
Тут лучше сразу джоинить на жанры и рейтинг MPA

2022-08-02 14:49 UTC, alexache commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "SELECT * FROM films;";
Здесь тоже нужен join на MPA и жанры

2022-08-02 19:24 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "SELECT * FROM films;";
готово

2022-08-02 19:25 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        String sql = "SELECT * FROM films WHERE id = ?";
готово

2022-08-02 19:36 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    List<Mpa> retrieveAllMpaRatings();
Готово

2022-08-02 19:57 UTC, SergeyAseev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmDbService.java
> +        return filmStorage.retrieveAllFilms().stream()
готово

2022-08-03 10:29 UTC, alexache approved these changes
Все ок, отличная работа!

2022-08-04 17:27 UTC, merged